version: '3'

services:
  win-server:
    image: windows/servercore:1709
    container_name: run-win-server
    volumes:
      - "./:/work/"
    ports:
      - "8080:8080"
    networks: 
      - sqldata-con
    depends_on:
      - sqldata
      
  dotnet-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: run-dotnet
    networks: 
      - sqldata-con
    depends_on:
      - sqldata

  pwsh:
    image: "mcr.microsoft.com/powershell"
    command: ["pwsh", "-File", "BuildDeleteAssets.ps1"]  
    volumes:
      - "./:/work/"  
    networks: 
      - sqldata-con
    depends_on:
      - sqldata

  sqldata:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      - SA_PASSWORD=pasword
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
      
networks:
  sqldata-con:
    driver: bridge
